### ISSUE TITLE
Error while extracting dataset

### ISSUE THREAD

**Issue by Optimist0** [nwpu-zxr/VadCLIP#1]
Hello Author,
Errors occur when unzipping both UCF-crime and XD-Violence.
Can you check or re-upload these datasets
Thank you.

**Comment by nwpu-zxr** [comment]
We have replaced the shared feature files and verified that there are no errors. You can re-download them on OneDrive. If any other errors occur, please inform us.

**Comment by TaylorLi123** [comment]
Hello author, your XD-Violence dataset training part is missing, please check and upload again
thank you
![0976a7c3766890f19908d0802eb5df1](https://github.com/nwpu-zxr/VadCLIP/assets/144213992/b808bf28-0c67-456d-9d6d-767d892cbb35)

**Comment by nwpu-zxr** [comment]
We have re-uploaded the feature files on OneDrive, but the files on Baidu-Netdisk has not been replaced yet. If the error files were downloaded from Baidu-Netdisk, please re-download the files shared by OneDrive.

**Comment by TaylorLi123** [comment]
Has been downloaded again, thank you for your reply

**Comment by xpwindells** [comment]
Hello author, thank you for your work, can you provide the clip to extract the video features of the code

**Comment by nwpu-zxr** [comment]
We use standard CLIP(ViT-B/16) to extract 10crop features of the videos.

**Comment by xpwindells** [comment]
> We use standard CLIP(ViT-B/16) to extract 10crop features of the videos.

Thank you for your reply, and I would like to ask about the clip frequency of the video. I calculated that the clip is every 16 frames, extract the features of the intercepted frames in turn, and save the numpy of float16 in the shape of frame number *512, is it correct?

**Comment by nwpu-zxr** [comment]
> > We use standard CLIP(ViT-B/16) to extract 10crop features of the videos.
> 
> Thank you for your reply, and I would like to ask about the clip frequency of the video. I calculated that the clip is every 16 frames, extract the features of the intercepted frames in turn, and save the numpy of float16 in the shape of frame number *512, is it correct?

Yes, previous works used i3D to extract features that each feature represents information within 16 frames, so we also sample features every 16 frames.
