### ISSUE TITLE
CLIP feature with the “10-crop” augment

### ISSUE THREAD

**Issue by ArielZc** [nwpu-zxr/VadCLIP#2]
Thanks to the authors for a great job. The provided CLIP feature is "10-crop" augment. 
（1）For UCF-Crime dataset and XD-Violence dataset, whether _0.npy is the center, _1~ _4.npy is the corners, and _5 ~ _9 is the mirrored counterparts? 
（2）Why is only "_5.npy' used in the test file "ucf_CLIP_rgbtest.csv" for the UCF-Crime data set, and only "_0.npy" is used in the test file "xd_CLIP_rgbtest.csv" for the XD-Violence data set?

**Comment by nwpu-zxr** [comment]
For question 1, yes. For question 2, because the result is better under the current settings.
