### ISSUE TITLE
Question About Test Results Obtained Using Provided Pretrained Weights

### ISSUE THREAD

**Issue by mycroft1603** [nwpu-zxr/VadCLIP#3]
Thanks for your time and for sharing your awesome work!
I've conducted tests using the provided pre-trained models and pre-extracted features, and it seems that the AUC in coarse-grained scenarios is lower than the results reported in the paper. 
If there some crucial steps I overlooked, or there are additional calculations required to achieve the results mentioned in the paper?
<img width="305" alt="test" src="https://github.com/nwpu-zxr/VadCLIP/assets/53992888/436b8566-4a6f-4037-94a1-1c00eec0a5b8">

**Comment by GP0123** [comment]
I use the Python version is 3.8 and PyTorch version is 2.0.0, but the auc is that
![1713676052602](https://github.com/nwpu-zxr/VadCLIP/assets/145019554/e8316b0a-47b8-4320-8d2c-2af4c88249b7)
it doesn't up to the result of the paper
